### ISSUE TITLE
Briefly describe your background in this area

### ISSUE THREAD

**Issue by sr320** [sr320/course-fish546-2018#1]

**Comment by kcribari** [comment]
I have listened to many people discuss bioinformatic and am aware of the information that can be gained from this type of analysis but do not how to do the analysis myself.

**Comment by laurahspencer** [comment]
Took your class in 2016- other than that I work with data sets primarily in R. 
Look forward to the class!

**Comment by magobu** [comment]
I have some experience with R, but not Python.
I have not used most of the other tools that are going to part of these class, so I hope that I can keep up with it! I'm ready to get immerse in this new world of bioinformatics!

**Comment by grace-ac** [comment]
I used Python a long time ago (feels like it) in 2014/2015 when I was practicing BLAST as a volunteer in your lab. I have used R in class (heavily guided) and have also used it more frequently with your and Sam's help, which has helped a lot more than the heavily guided class format because I had some time to muddle through it and struggle on my own, which helps me learn.

**Comment by yaaminiv** [comment]
Worked with -omics datasets (transcriptomic, proteomic, epigenomic) datasets before, and I feel comfortable using Jupyter and R Markdown. I want to get more practice working in the command line and understand how to determine which pipelines and commands to use, and know why I'm making that decision.

**Comment by hgloiselle** [comment]
I've used R, Python, and terminal before, but need much more practice. I know what information can be learned by using bioinformatics, but don't know how to actually do it.

**Comment by zscooper** [comment]
I have learned some basics in python and R through free online courses, and am familiar with command line operations through persistent searching of commands while needing to use it. I am currently working with a fairly large amplicon dataset and use several command line tools regularly. I feel like I'm not using these tools to their maximum potential at the moment and would like to become more familiar with scripting and writing batch files for automation.

**Comment by calderatta** [comment]
I have some experience using R (FISH 522/523 and research projects), and to a lesser degree python and terminal (online courses), but haven't had experience handling any of the datasets in the bioinformatics umbrella.

**Comment by melodysyue** [comment]
I am very comfortable with R. I had some exposure to python and bash, but mostly self-taught. I have experiences with DADA2 pipeline for microbiome analyses.

**Comment by wsano16** [comment]
I have experience with the command line and R via coursework in phylogenetics and biostatistics, and I applied both tools in my previous work experience doing microbiome analysis.

**Comment by jgardn92** [comment]
I have some experience working with small data sets (barcoding genes) using a gui but no experience with larger data sets. I have some experience with using R but no experience with python or bash.

**Comment by kimh11** [comment]
I have experience in R working on genetic analysis and python working on non-biology projects. I've analyzed genomic data using a mix of on DNAnexus GUI, shell scripting, and R.

**Comment by Jeremyfishb** [comment]
I have almost no experience with bioinformatics. I've done protein extractions and have a bunch of data about which proteins are in a batch of samples but have no idea how to handle them and what to do next.
