### ISSUE TITLE
Create an Issue

### ISSUE THREAD

**Issue by sr320** [sr320/course-fish546-2018#10]
Identify at least one issue you would like assistance on relating to one of the following topics
- Bash 
- GitHub
- Jupyter
- Your data

It could be how to do a simple task, improve your current workflow, reduce redundant actions, or a simple curiosity etc.
**Once you [create an issue](https://github.com/sr320/course-fish546-2018/issues/new)**

add the url below

**Comment by grace-ac** [comment]
Grace's "[terminology help?](https://github.com/sr320/course-fish546-2018/issues/16)" issue

**Comment by yaaminiv** [comment]
[Jupyter notebook widgets](https://github.com/sr320/course-fish546-2018/issues/17)

**Comment by kimh11** [comment]
My issue on [data backup](https://github.com/sr320/course-fish546-2018/issues/18)

**Comment by Jeremyfishb** [comment]
[Connecting Jupyter and Git Bash](https://github.com/jupyter/notebook/pull/3087 )

**Comment by laurahspencer** [comment]
laura's [jupyter vs. rmarkdown issue](https://github.com/sr320/course-fish546-2018/issues/20)

**Comment by kcribari** [comment]
[GitHub Navigation](https://github.com/sr320/course-fish546-2018/issues/21#issue-369269874)

**Comment by wsano16** [comment]
Will's issue: file structure in RStudio https://github.com/sr320/course-fish546-2018/issues/22

**Comment by jgardn92** [comment]
Jenny's [running Ubuntu on Windows issue](https://github.com/sr320/course-fish546-2018/issues/23)

**Comment by hgloiselle** [comment]
[laptop computing abilities](https://github.com/sr320/course-fish546-2018/issues/24)

**Comment by zscooper** [comment]
[Local or remote processing of jobs?](https://github.com/sr320/course-fish546-2018/issues/25)

**Comment by calderatta** [comment]
[Estimating job time](https://github.com/sr320/course-fish546-2018/issues/26)

**Comment by magobu** [comment]
[Jupiter not working on Windows](url)

**Comment by melodysyue** [comment]
* [Advantages of Jupyter over Rmarkdown](https://github.com/sr320/course-fish546-2018/issues/29)
* [How to render LaTex math equations in github markdown?](https://github.com/sr320/course-fish546-2018/issues/28)
