### ISSUE TITLE
Unix commands

### ISSUE THREAD

**Issue by sr320** [sr320/course-fish546-2018#12]
What does the second line of the following code do?

```
tr -cs A-Za-z '\n' |
tr A-Z a-z |
sort |
uniq -c |
sort -rn |
sed ${1}q
```

**Comment by grace-ac** [comment]
The second line translates (changes) all uppercase letters to lowercase letters.

**Comment by magobu** [comment]
> Translate all uppercase letters to lowercase
from chapter 7 in our textbook. The whole  7 line Unix scrip, by McIlroy, was a  reply to the seven-page _literate program_  to count and write the _k_ most common word in a file written by Knuth.


 

>

**Comment by yaaminiv** [comment]
Converts all uppercase letters to lowercase letters

**Comment by kimh11** [comment]
Converts all uppercase letters (A-Z) to lowercase (a-z) and send the standard output to the next command.

**Comment by Jeremyfishb** [comment]
Translates all upper case letters to lower case letters and send the standard output to the next command.

**Comment by kcribari** [comment]
The line tr A-Z a-z | translates the uppercase alphabet to a lowercase alphabet in the pipeline.

**Comment by hgloiselle** [comment]
it translates the uppercase letters to lowercase ones.

**Comment by wsano16** [comment]
It translates all uppercase letters to lowercase letters and passes the output via a pipe to the next line of code.

**Comment by jgardn92** [comment]
It translates all characters that are UPPER CASE alphabet letters to lowercase alphabet letters.

**Comment by zscooper** [comment]
This line of code uses the translate function `tr` to change all UPPERCASE letters to lowercase.

**Comment by calderatta** [comment]
The second line of code takes the input from the previous line, and translates (using the 'tr' function) all uppercase letters ('A-Z') to lowercase letters ('a-z'), then pipes the output to the following command.

**Comment by melodysyue** [comment]
The second line of code `tr A-Z a-z |` translates all UPPERCASE letters to lowercase.

**Comment by laurahspencer** [comment]
Yes what they said, translates/converts uppercase to lowercase. (sorry, late to the game here)
