### ISSUE TITLE
Terminology help?

### ISSUE THREAD

**Issue by grace-ac** [sr320/course-fish546-2018#16]
What are the differences (if any) between the following terms:     
- bash
- unix
- shell
- terminal

**Comment by sr320** [comment]
Great question

from 
https://swcarpentry.github.io/shell-novice/01-intro/index.html

> A shell is a program like any other. What’s special about it is that its job is to run other programs rather than to do calculations itself. The most popular Unix shell is Bash, the Bourne Again SHell (so-called because it’s derived from a shell written by Stephen Bourne). Bash is the default shell on most modern implementations of Unix and in most packages that provide Unix-like tools for Windows.

that cover most of the terms. 
Terminal is an application on the Mac OS.
> Terminal provides a command line interface to control the UNIX-based operating system that lurks below macOS (or Mac OS X). 
via https://www.macworld.co.uk/how-to/mac-software/how-use-terminal-on-mac-3608274/
