### ISSUE TITLE
Widgets for Jupyter Notebook

### ISSUE THREAD

**Issue by yaaminiv** [sr320/course-fish546-2018#17]
Anyone use widgets in Jupyter notebook they like? I'm curious.

**Comment by sr320** [comment]
Do you mean widgets? 
https://ipywidgets.readthedocs.io/en/stable/examples/Widget%20Basics.html

or Extensions
if the latter I have only added one of many... ExecuteTime
![ex](https://d.pr/i/eXvgK9+)
