### ISSUE TITLE
Best way to backup data

### ISSUE THREAD

**Issue by kimh11** [sr320/course-fish546-2018#18]
How do you back up your data?
1. Where is it stored - server, cloud, trusty external hard drive, or all of the above?
2. What system/strategy do you use? For example, should I use different back up methods of original sequence data vs intermediate files?

**Comment by laurahspencer** [comment]
This is what I do, but it's by no means ideal: 
- I have an external hard drive that automatically backs up my computer when I connect them, via TimeMachine (Apple).  This requires that I remember to plug my computer in, so not ideal.  
- All my data/project files are GitHub repos. I work locally on my computer, then commit and push updates to the "Master" in the Cloud. Limitation is that I can't push any files >100MB (those are saved locally, and backed up on the Cloud or our lab server separately). 
- All my manuscripts etc. are Google Docs, so I can access them from any computer. I am now realizing that should Google be compromised, I would not have any backups of them!
