### ISSUE TITLE
What do you hope to get out of the class?

### ISSUE THREAD

**Issue by sr320** [sr320/course-fish546-2018#2]

**Comment by kcribari** [comment]
I hope to gain an understanding of bioinformatics, how to deal and analyze data that I am given on my own, and be able to solve problems efficiently.

**Comment by laurahspencer** [comment]
1. I haven’t used really any of the bash language (except simple github commands) since taking your class 2 years ago, so I look forward to a refresh 
2. Work through my RNAseq data from Katherine 
3. If possible, convert to R Markdown (from Jupyter notebook) 
3. Absorb other helpful info

**Comment by magobu** [comment]
Get a good foundation on data analysis so I am able to analyze my own data without having to rely completely on data scientists friends.

**Comment by grace-ac** [comment]
Get a better understanding of how bioinformatics and R works, as well as get some good practice so that I can have a good workflow and resources for when I analyze data down the road

**Comment by yaaminiv** [comment]
My goal is to get a better understanding of bisulfite sequencing data analysis and create reproducible workflows for Bismark, methylKit, and IGV analysis by analyzing MBD bisulfite seq data from my *C. virginica* project

**Comment by hgloiselle** [comment]
I'd like to become somewhat competent with bioinformatic methods so that I am able to analyze my own data sets in the future.

**Comment by zscooper** [comment]
I've self-taught a lot of command line operations and basics in python and R, but I'd like to gain a more official understanding of file manipulation through the command line. I think it would also be useful to learn about good habits for keeping records and reporting analysis operations and pipelines and in publications.

**Comment by calderatta** [comment]
I would like to become more knowledgable and proficient with the methods used for handling bioinformatics problems. My short term goal is to use these skills for my graduate thesis, for which I will be constricting a phylogeny using 4483 nuclear markers (exon-capture). I would also like to learn skills that I can carry into future projects, such as how to structure methods to be more reproducible and less prone to error.

**Comment by melodysyue** [comment]
Get a better understanding of bioinformatics, bash, and python. I would also like to learn skills to handle big data and cloud computing.

**Comment by wsano16** [comment]
I want to understand the theory behind general bioinformatics pipelines to the extent that I feel comfortable and knowledgeable about using non-default parameters.

**Comment by jgardn92** [comment]
I want to become more comfortable with command line and generally best practices when handling large data sets. I also would ideally like to develop the skills to analyze my exon-capture data set that I will be generating for my thesis

**Comment by kimh11** [comment]
My goals for the class are to:
1. Create **reproducible** pipelines for whole genome sequencing (WGS) data
2. Understand how to decide between analysis on the cloud vs my computer
3. Get a better understanding of the bioinformatics pipelines used for different datasets

**Comment by Jeremyfishb** [comment]
I hope to learn the bioinformatics tools that allow me to handle, process and examine proteomics data for current and future projects.
