### ISSUE TITLE
Jupyter notebook vs. RMarkdown

### ISSUE THREAD

**Issue by laurahspencer** [sr320/course-fish546-2018#20]
I'm curious if people have strong feelings between Jupyter notebooks and RMarkdown?  

I really like RMarkdown's ease of use, GUI interface in RStudio, and the easy ability to work in a project and share entire project folders between computers, if needed.   Also, I can open the file in Markdown editor to quickly review/check some code.  While I have yet to really use bash in RMarkdown, I understand that it's possible.  Also, I do most of my data analysis in R, and it'd be great to keep things contained. 

Jupyter notebook files are clunky to me, but perhaps I'm not maximizing its capacity. What am i missing out on if I don't use it?

**Comment by yaaminiv** [comment]
Whenever I use R Markdown to run really intensive commands (ex. blast) it takes much longer than it would on Jupyter, and sometimes R crashes. You also can't tab complete within a bash chunk in R Markdown (which I think is pretty horrible)
