### ISSUE TITLE
Consistent file structure/working directory when using R and bash blocks in RStudio

### ISSUE THREAD

**Issue by wsano16** [sr320/course-fish546-2018#22]
Is it possible switch between blocks of bash code and new blocks of bash code in RStudio while keeping consistent working directory? Or do I have to re-establish my working directory in every new block? Furthermore, is it possible to migrate between blocks of R and bash code without reverting back to my user directory?

**Comment by sr320** [comment]
> Is it possible switch between blocks of bash code and new blocks of bash code in RStudio while keeping consistent working directory? 

Best practices is working in projects and _NOT_ setting wd in R studio. (We can go over next week - but see http://r4ds.had.co.nz/workflow-projects.html)

> Or do I have to re-establish my working directory in every new block? 

see above.

> Furthermore, is it possible to migrate between blocks of R and bash code without reverting back to my user directory? 

yes
