### ISSUE TITLE
Running Ubuntu on Windows 10

### ISSUE THREAD

**Issue by jgardn92** [sr320/course-fish546-2018#23]
I have installed and successfully opened Ubuntu to run Linux on my Windows computer. However, I'm a little confused as to where it is actually residing on my machine. According to the `pwd` when it first opens I am in `/home/jenny` but I am not sure how I  would go about accessing other things on my machine, like the blast tutorial work we did today, or Anaconda3 and the Jupyter notebook. Running `echo $PATH` gives me a long list like it did in GitBash but now the directories from my C drive have a preceding directory.
`/mnt/c/Program Files/` 
What does this mean? When I try to list what is in the mnt directory I get errors saying `ls: cannot read symbolic link 'mnt/c/Documents and Settings': Permission denied` . Also not sure what this means. Any help would be greatly appreciated!

**Comment by sr320** [comment]
Great question!
Running Ubuntu on Windows is something I do not have experience with.
We can look at in class next week.
You could start by having Linux bash terminal open, and explore (while looking at Windows Explorer)
lots of `cd` and `ls`. 

If you want to, you could install `tree` where you can "see" directory structure.
http://mama.indstate.edu/users/ice/tree/

**Comment by kubu4** [comment]
Very cool that you have this running! I'm definitely curious to see what you think.

I think you can get around the permissions error by launching Ubuntu with Adminstrator privileges. Do this by right-clicking on the Ubuntu app and then select "Run as Administrator".

To quickly fix the Anaconda/Jupyter/Bit Bash issue, please see my most recent post in #19. That should fix that problem.

**Comment by Jeremyfishb** [comment]
Hi All,

I also installed Ubuntu and had the same problem initially. I can't remember the exact steps I used to get it working but found this nifty bit of code that helped: 
"sudo apt-get update && sudo apt-get install bash" (without the quotation marks)
heres's a [link](https://askubuntu.com/questions/529563/shellshock-bash-already-updated) to where I found the code.
I'm not positive that that's what fixed your specific problem but a lot of things started working after that and I was able to complete the bash tutorial. Also, you can use this code: 
sudo apt install ncbi-blast+
then you don't have to specify the path (or create a bldir) to run blastx, you can just use the command blastx
However, I still cannot get Jupyter to link to Ubuntu...

**Comment by kubu4** [comment]
To work with Jupyter notebooks from your Ubuntu installation, you need to install Anaconda from your Ubuntu terminal.

1. Open Ubuntu.

2. Run the following command to download the Anaconda installer:

```wget https://repo.anaconda.com/archive/Anaconda3-5.3.0-Linux-x86_64.sh```

3. Type the following to install Anaconda. This will require you to answer some questions (you can say "no" to the Microsoft VisualStudio code thingy question) and will take a _long_ time!

```bash Anaconda3-5.3.0-Linux-x86_64.sh```

4. Quit and restart Ubuntu.

5. Type the following to launch a Jupyter notebook:

```jupyter notebook```

6. Read the text on the terminal! You'll have to copy and paste a weird URL into your browser. Then you're good to go!

After this, feel free to delete the Anaconda installer file (Anaconda3-5.3.0-Linux-x86_64.sh).

**Comment by magobu** [comment]
Hey Sam! I did follow your instructions and It seems to be working! I can get jupyter notebook within Unbutu! but how do I save the text I type if I had a need to do so?

Also, in order to get Anaconda so I can launch it from my desktop, how do I do that? 

Thanks!

**Comment by kubu4** [comment]
>  but how do I save the text I type if I had a need to do so?

This happens semi-automatically when using Jupyter notebooks. When you start a new notebook, a notebook file (.ipynb) is created in whichever directory you're currently in. As you run stuff in the notebook, Jupyter autosaves the .ipynb file. However, there's also a little icon (towards the left side of the notebook menu bar) of a diskette; click this to save the file.

When you re-open this notebook at a later date, all of you input and output will still be present.

> Also, in order to get Anaconda so I can launch it from my desktop, how do I do that?

Can't be done. Just resign yourself to always using the command line to run any/all programs for this bioinformatics stuff. So, always launch a Jupyter notebook from a terminal.

**Comment by jgardn92** [comment]
I am going back to using Ubuntu but I'm trying to get it to run on my desktop computer. Currently I have Windows Enterprise version 1803 and from some cursory searching it should be able to support Linux. Currently when I try to run Linux I get and error saying
"WslRegisterDistribution failed with error: 0x8007019e
The Windows Subsystem for Linux optional component is not enabled. Please enable it and try again."
I'm currently looking in to how to enable Windows Subsytem for Linux but am currently not having much luck.
Any advice?

**Comment by kubu4** [comment]
Try steps 1 and 2 on this page:

https://docs.microsoft.com/en-us/windows/wsl/install-win10

Follow these instructions to launch PowerShell as Adminstrator:

https://www.thewindowsclub.com/how-to-open-an-elevated-powershell-prompt-in-windows-10

**Comment by jgardn92** [comment]
Thank you! It worked. I had tried the PowerShell step before but had missed the crucial run as administrator step.
