### ISSUE TITLE
laptop computing ability 

### ISSUE THREAD

**Issue by hgloiselle** [sr320/course-fish546-2018#24]
I was just curious if when our computer is running a program, like blast, if it has to stay open and awake while the program is running which can take hours. how much can a personal computer actually do bioinformatics wise or do we have to get onto a cluster?

**Comment by laurahspencer** [comment]
I use a Macbook Pro 2011 (dual processor, only 4GB memory), and am able to handle basic programs like blast, downloading large files via curl, etc.
