### ISSUE TITLE
When is it appropriate to switch between local processing and remote work on an HPC?

### ISSUE THREAD

**Issue by zscooper** [sr320/course-fish546-2018#25]
I primarily run computational jobs locally on my macbook. It has a powerful enough processor to run most jobs, but I've occasionally run myself into week long processing jobs (distancing sequencing reads, clustering them, or creating phylogenetic trees) that render my macbook basically useless to me. 

How big does a project have to get for it to be reasonable to use a remote HPC rather than patiently running jobs locally? I realize this is usually project and job specific, so I'm looking more for abstract guidelines on this type of decision.

**Comment by kubu4** [comment]
Unfortunately, there isn't too much of a guide on this, as it can vary so greatly depending on your job. If you have access to, and understand how to use, a high performance computing (HPC) cluster, you should probably just use that.

Other bioinformatics-related activities (such as "basic" text processing, sorting, joining, file splitting, etc) can usually be handled by a personal computer without lengthy processing times.
