### ISSUE TITLE
How can I use Jupiter in Windows

### ISSUE THREAD

**Issue by magobu** [sr320/course-fish546-2018#27]
Just wondering what is the solution for making Jupiter work with Windows

**Comment by kubu4** [comment]
See these two issues to get it working (i.e. ability to use bash in Jupyter notebook):

1. [Uninstall/Re-install Anaconda](https://github.com/sr320/course-fish546-2018/issues/19#issuecomment-429136483). This works with a Git Bash installation.

2. [Install Ubuntu and Anaconda for Linux](https://github.com/sr320/course-fish546-2018/issues/23#issuecomment-429480845). This will require you to install Ubuntu on Windows 10; search the internet for the steps to do this.

I think the second way would be ideal, but is not necessary.
