### ISSUE TITLE
Getting Set-Up

### ISSUE THREAD

**Issue by sr320** [sr320/course-fish546-2018#3]
Here are _some_ of the tasks for this week, 
- [ ] GitHub Account, Install Local GitHub client
- [ ] Bash Installed
- [ ] Become familiar with Markdown
- [ ] Install good Text Editor
- [ ] Install good Markdown Editor

Once completed, respond with
1. Your OS
2. Your Text Editor
3. Your Markdown Editor

**Comment by magobu** [comment]
Hi Steven,

1. My OS: Windows 10
2. Text editor: Sublime text 3
3. Markdown editor: Markdown 2

Looking forward to this class!

**Comment by kcribari** [comment]
Hi!

1. OS: macOS High Sierra
2. Text Editor: Sublime Text
3. Markdown editor: Atom

Kelly

**Comment by laurahspencer** [comment]
1. Mac OS
2. Text Wrangler
3. Mou

**Comment by grace-ac** [comment]
1. macOS High Sierra, version 10.13.6
2. Text Wrangler
3. Atom

**Comment by yaaminiv** [comment]
1. MacOS El Capitan 10.11.16
2. TextWrangler
3. Mou

**Comment by hgloiselle** [comment]
1. MacOS
2. BBEdit
3. Atom

**Comment by zscooper** [comment]
1. MacOS
2. Sublime Text
3. Atom

**Comment by calderatta** [comment]
1. MacOS High Sierra 10.13.6
2. BBEdit
3. Atom

**Comment by melodysyue** [comment]
Hi Steven,
1. My OS: MacOS
2. My Text Editor: Sublime Text
3. My Markdown Editor: Atom

**Comment by jgardn92** [comment]
Hi Steven,
1. My OS: Windows 10
2. My Text Editor: Notepad++
3. My Markdown Editor: MarkdownPad 2

**Comment by kimh11** [comment]
1. MacOS High Sierra
2. Sublime Text
3. Atom

**Comment by wsano16** [comment]
1. MacOS Sierra
2. Sublime Text
3. Atom

**Comment by Jeremyfishb** [comment]
1. Windows 10
2. Notepad ++
3. Markdown Pad 2
