### ISSUE TITLE
Repository directory structure

### ISSUE THREAD

**Issue by sr320** [sr320/course-fish546-2018#31]
Please post a screenshot that demonstrates the directory structure of your class repo on your local machine.

**Comment by Jeremyfishb** [comment]
![image](https://user-images.githubusercontent.com/43756452/47052446-31a71f80-d15d-11e8-9947-bfe9afa1c75e.png)

**Comment by kcribari** [comment]
<img width="512" alt="screen shot 2018-10-16 at 3 49 59 pm" src="https://user-images.githubusercontent.com/43479654/47051935-3c60b500-d15b-11e8-80c2-a2d98e88fa4c.png">

**Comment by hgloiselle** [comment]
<img width="566" alt="screen shot 2018-10-16 at 3 41 31 pm" src="https://user-images.githubusercontent.com/43651113/47051664-040ca700-d15a-11e8-8a63-0abc6d0c1410.png">

**Comment by yaaminiv** [comment]
<img width="564" alt="untitled" src="https://user-images.githubusercontent.com/22335838/47051904-1affc900-d15b-11e8-8186-7e44a12d5b73.png">

**Comment by magobu** [comment]
![image](https://user-images.githubusercontent.com/42585702/47052382-da08b400-d15c-11e8-87ee-1633d030f944.png)

**Comment by magobu** [comment]
![image](https://user-images.githubusercontent.com/42585702/47052557-c01ba100-d15d-11e8-8d63-1ef8097006a8.png)

**Comment by laurahspencer** [comment]
![image](https://user-images.githubusercontent.com/17264765/47119952-d854f400-d221-11e8-89bc-372e37d84d02.png)

**Comment by jgardn92** [comment]
![directorystructure](https://user-images.githubusercontent.com/43687198/47174933-dabd5980-d2c6-11e8-91a4-d961e00b7bfc.JPG)

**Comment by calderatta** [comment]
<img width="511" alt="screen shot 2018-10-18 at 1 53 25 pm" src="https://user-images.githubusercontent.com/43666087/47183585-4c080700-d2dd-11e8-941a-7e26326bedc6.png">

**Comment by grace-ac** [comment]
![screen shot 2018-10-19 at 2 32 43 pm](https://user-images.githubusercontent.com/14934314/47244881-ffd7c800-d3ab-11e8-9ea1-e1201d68a603.png)

**Comment by wsano16** [comment]
![image](https://user-images.githubusercontent.com/17071359/47244999-652bb900-d3ac-11e8-97bd-60065fbbbe49.png)

**Comment by kimh11** [comment]
<img width="415" alt="screen shot 2018-10-19 at 7 32 29 pm" src="https://user-images.githubusercontent.com/13041680/47250678-c66a8100-d3da-11e8-8abb-6480e9d2e906.png">

**Comment by melodysyue** [comment]
<img width="571" alt="screen shot 2018-10-20 at 8 37 35 am" src="https://user-images.githubusercontent.com/35020018/47257507-90adb280-d443-11e8-835e-5e48b489c6b4.png">
