### ISSUE TITLE
Readme Completion

### ISSUE THREAD

**Issue by sr320** [sr320/course-fish546-2018#32]
For your repository, please provide a detailed Readme that includes

* General Description of your project including goals and objectives
* A description of your repository structure, including what each directory includes, and describing any unique files.
* A projected timeline for what you plan to accomplish in weeks 4 and 5.

Once you have updated said Readme, add url below.
Feel free to ask for any clarifications, tomorrow during class.

**Comment by melodysyue** [comment]
My updated [README.](https://github.com/fish546-2018/Yue-metabarcoding/blob/master/README.md)

**Comment by hgloiselle** [comment]
my [readme](https://github.com/fish546-2018/hope-whales/blob/master/README.md)

**Comment by yaaminiv** [comment]
My [README](https://github.com/fish546-2018/yaamini-virginica/blob/master/README.md)

**Comment by Jeremyfishb** [comment]
My updated [readme](https://github.com/Jeremyfishb/Jeremy-coral/blob/master/README.md)

**Comment by kcribari** [comment]
Updated [readme](https://github.com/fish546-2018/Cribari-eDNA/blob/master/README.md)

**Comment by laurahspencer** [comment]
Laura's [readme](https://github.com/fish546-2018/laura-quantseq/blob/master/README.md)

**Comment by jgardn92** [comment]
My [readme](https://github.com/fish546-2018/Jenny-Snailfish/blob/master/README.md)

**Comment by calderatta** [comment]
My [readme](https://github.com/fish546-2018/calder-exon-capture/blob/master/README.md)

**Comment by grace-ac** [comment]
Grace's [readme](https://github.com/fish546-2018/grace-Cbairdi-transcriptome/blob/master/README.md)

**Comment by wsano16** [comment]
my [readme](https://github.com/fish546-2018/will-Chiru16S/blob/master/README.md)

**Comment by kimh11** [comment]
My [readme](https://github.com/fish546-2018/hj-pangolin/blob/master/README.md)

**Comment by magobu** [comment]
My [readme](https://github.com/fish546-2018/marta-eDNA/edit/master/README.md)
