### ISSUE TITLE
Punchcard

### ISSUE THREAD

**Issue by sr320** [sr320/course-fish546-2018#33]
Take a screenshot of your class repo commits.. and post below
eg https://github.com/sr320/course-fish546-2018/graphs/commit-activity

**Comment by kcribari** [comment]
<img width="1031" alt="screen shot 2018-10-16 at 7 32 53 pm" src="https://user-images.githubusercontent.com/43479654/47058538-5f4e9180-d17a-11e8-8ea0-a0b72d71a759.png">

**Comment by laurahspencer** [comment]
![image](https://user-images.githubusercontent.com/17264765/47122631-777ee900-d22c-11e8-8e9c-ea18800179b4.png)

**Comment by Jeremyfishb** [comment]
![image](https://user-images.githubusercontent.com/43756452/47166137-552eaf00-d2b0-11e8-93a9-a335423f4738.png)

**Comment by yaaminiv** [comment]
<img width="1018" alt="screen shot 2018-10-18 at 9 28 56 am" src="https://user-images.githubusercontent.com/22335838/47169413-4815be00-d2b8-11e8-9747-36588a4210ed.png">

**Comment by hgloiselle** [comment]
<img width="749" alt="screen shot 2018-10-18 at 10 11 15 am" src="https://user-images.githubusercontent.com/43651113/47171703-45b66280-d2be-11e8-9295-cf9fe43529a7.png">

**Comment by jgardn92** [comment]
![commits](https://user-images.githubusercontent.com/43687198/47178881-52908180-d2d1-11e8-830b-531962a2632b.JPG)

**Comment by calderatta** [comment]
![screen shot 2018-10-18 at 2 52 22 pm](https://user-images.githubusercontent.com/43666087/47186454-778eef80-d2e5-11e8-8e00-cd33ab24c0fd.png)

**Comment by wsano16** [comment]
![image](https://user-images.githubusercontent.com/17071359/47246369-2862c080-d3b2-11e8-8e62-41a3594b77ed.png)

**Comment by grace-ac** [comment]
![screen shot 2018-10-19 at 3 40 53 pm](https://user-images.githubusercontent.com/14934314/47246939-7200da80-d3b5-11e8-8b9b-151929cf1324.png)

**Comment by kimh11** [comment]
<img width="1022" alt="screen shot 2018-10-19 at 8 11 34 pm" src="https://user-images.githubusercontent.com/13041680/47250704-35e07080-d3db-11e8-8e11-2f1914e798be.png">

**Comment by melodysyue** [comment]
<img width="1440" alt="screen shot 2018-10-20 at 8 28 23 am" src="https://user-images.githubusercontent.com/35020018/47257405-247e7f00-d442-11e8-80df-0b30c568b7a2.png">

**Comment by melodysyue** [comment]
![my commits](https://github.com/fish546-2018/Yue-metabarcoding/graphs/commit-activity)

**Comment by melodysyue** [comment]
<img width="1458" alt="screen shot 2018-10-20 at 8 33 11 am" src="https://user-images.githubusercontent.com/35020018/47257453-da49cd80-d442-11e8-94cb-ec90f3fb8270.png">

**Comment by magobu** [comment]
![image](https://user-images.githubusercontent.com/42585702/47270432-8dd4bf80-d520-11e8-8771-d354c1d9569e.png)
