### ISSUE TITLE
Counting sequences in many fasta or fastq files

### ISSUE THREAD

**Issue by calderatta** [sr320/course-fish546-2018#35]
I'm trying to find read counts for each of the fastq files that I have. Right now, I'm using `grep` on the `@` character but I'm not sure how to do this for multiple files.

**Comment by sr320** [comment]
Here is some useful code: https://github.com/RobertsLab/code/blob/master/fasta.md

I think this code for fastq
for fastq files: `awk '{s++}END{print s/4}' file.fastq`
via https://www.biostars.org/p/139006/

I normally just use fastQC output to know number of reads.

using a for loop something like

```
%%bash
for f in /where/your/files/r/*fq
do
awk '{s++}END{print s/4}' $f
done
```

**Comment by kubu4** [comment]
```grep``` can process a list of files.

Here's an example for fastq files:

```grep -c '@' *.fq```

This will search for the ```@``` symbol in any files ending with ```.fq``` and will print the filename and the number of results for each file.

**Comment by kubu4** [comment]
"Pro" tip -

Most FastQ files comes compressed as ```gzip``` files.

Use ```zgrep -c '@' *.fq.gz``` to search through compressed FastQ files.
