### ISSUE TITLE
FastQC

### ISSUE THREAD

**Issue by sr320** [sr320/course-fish546-2018#37]
What do you find to be the most useful output of FastQC (we will cover in class Tuesday).

**Comment by yaaminiv** [comment]
![screen shot 2018-10-22 at 1 54 48 pm](https://user-images.githubusercontent.com/22335838/47318905-2a22c300-d602-11e8-8bbf-83f0ed3b0bcd.png)

I really like the per-base sequence quality output. It's the easiest way for me to see how quickly sequence quality degrades, and determine if quality-trimming did anything useful.

**Comment by hgloiselle** [comment]
I find both the GC content and sequence length output interesting. Ancient DNA generally tends to have a higher GC content than modern DNA so it will be neat to see what my future data will show with regards to this. Sequence length is also of interest in ancient DNA studies and it will be useful to use FastQC to gain an understanding of the distribution of fragment lengths.

**Comment by kcribari** [comment]
I find the sequence length distribution to be useful. This is just a visual check that all of the sequences are the correct length or the CO1 target sequences that we want to analyze. The small peak at 75 bp most likely represent unpaired adaptors that were not cleaned out during library preparation.

<img width="755" alt="screen shot 2018-10-25 at 10 42 05 am" src="https://user-images.githubusercontent.com/43479654/47520828-27b0ab00-d846-11e8-8870-10daf6f1688e.png">

**Comment by jgardn92** [comment]
The per base sequence content. It shows that I have some contamination (probably and adapter) at the start of my sequences. 
![fastqc-answer](https://user-images.githubusercontent.com/43687198/47528914-3eadc800-d85b-11e8-90c9-ccd45808e4d8.JPG)

**Comment by Jeremyfishb** [comment]
Though I will probably not be using fastqc in my own analyses, I think the first output, per base sequence quality, gives me the most striking first impression about quality of the sequence reads with regards to sequence lengths.

**Comment by wsano16** [comment]
![image](https://user-images.githubusercontent.com/17071359/47535339-fc42b600-d86f-11e8-89b5-1c76786a643a.png)
I most appreciate the per base sequence content readout because it is a quick and easy way to determine if you have any primer or adapter contamination in your reads. It seems like what is considered "raw" data varies between sequencing cores (primer/adapter trimmed vs. untrimmed), so a quick pass through FastQC can tell you the state of your data.

**Comment by magobu** [comment]
Like some other have mentioned the first plot of per base sequence quality is the one I found the most helpful. But I liked too the one that shows the sequence content, for contamination.
![image](https://user-images.githubusercontent.com/42585702/47539884-674bb700-d887-11e8-813a-a39e65ab7893.png)

![image](https://user-images.githubusercontent.com/42585702/47539942-a67a0800-d887-11e8-90e1-e962a33e116d.png)

**Comment by calderatta** [comment]
I think the per base sequence quality and content. These two outputs are the most intuitive to me, help verify read length, and are helpful when determining what sections to trim. Sequence quality shows what parts of the reads are the most reliable and you can see the natural degradation over the sequence. The sequence content helps determine where adapter contamination might be.

<img width="856" alt="screen shot 2018-10-26 at 10 36 09 pm" src="https://user-images.githubusercontent.com/43666087/47600088-bae5ff80-d970-11e8-811a-f726379937eb.png">
<img width="852" alt="screen shot 2018-10-26 at 10 36 26 pm" src="https://user-images.githubusercontent.com/43666087/47600089-bae5ff80-d970-11e8-836e-99291750d27e.png">

**Comment by laurahspencer** [comment]
The first plot showing quality score seems to be most useful. I also find the color-coding helpful (e.g. :x:, :white_check_mark:, etc.) 

Here's is a screen shots of fastqc results from an untrimmed fastq file: 

![image](https://user-images.githubusercontent.com/17264765/47600763-1d43fd80-d97b-11e8-988b-6f4ec50a511b.png)

And the same data trimmed: 

![image](https://user-images.githubusercontent.com/17264765/47600770-28972900-d97b-11e8-9b71-d67b89ba3d26.png)

**Comment by melodysyue** [comment]
Three output figures that I have found are particularly useful: 
**1) Per base quality**: to quick check sequence quality and help decide trimming criteria; 
**2) Per base sequence content**: to quick check untrimmed adapters/primers or possible contamination; 
**3) Sequence Duplication Levels**: to quick check sequence diversity in my samples. 
Here is an example of using FastQC to examine my sequences. 
![picture1](https://user-images.githubusercontent.com/35020018/47672076-4973a000-db6e-11e8-9879-bd37156f4e96.png)

**Comment by grace-ac** [comment]
I really like the quality scores, because it's easy to check if the sequences are in the green (good). 

But all outputs have something useful to show, and [this manual](https://dnacore.missouri.edu/PDF/FastQC_Manual.pdf) helps explain what the different outputs mean.

**Comment by kimh11** [comment]
The two I like are: 1. per base sequence quality and 2. sequence duplication levels.
Per base sequence quality makes it easy to check the quality of reads before and after trimming and sequence duplication levels give me a quick overview about the level of coverage and check for PCR duplication.

![quiz1](https://user-images.githubusercontent.com/13041680/47959052-5beb4080-df97-11e8-9e8b-197ffa310918.png)
![quiz](https://user-images.githubusercontent.com/13041680/47959053-60175e00-df97-11e8-80f9-77c273f6562e.png)
