### ISSUE TITLE
Tuesday's jupyter notebook with fastqc tutorial?

### ISSUE THREAD

**Issue by laurahspencer** [sr320/course-fish546-2018#42]
@sr320 did you save your Jupyter notebook from Tuesday's tutorial showing how to use fastqc in the command line?

**Comment by sr320** [comment]
Yes
https://github.com/fish546-2018/steven-clam/blob/master/FastQC.ipynb

On Mac, be sure to download .zip version of fastqc.

**Comment by laurahspencer** [comment]
# :metal:
