### ISSUE TITLE
Mox question - gscratch

### ISSUE THREAD

**Issue by kimh11** [sr320/course-fish546-2018#43]
I have an account through the Research Computing Club and use the STF nodes. 

What is the difference between /gscratch/scrubbed and /gscratch/stf/myowndirectory? 

I was told to create my own directory in gscratch/stf/ to keep large files temporarily. Does it matter where I store my fastq files for analyses?

**Comment by sr320** [comment]
`scrubbed` is automatically deleted in 30 days - but is large.
Not sure exactly how much space stf has... I imagine quite a bit.

If they say use stf - I would do that. Here is more info on how our lab uses mox space including my suggestion for organization

https://github.com/RobertsLab/hyak_mox/wiki/Data-Storage-&-System-Organization
