### ISSUE TITLE
Remote Computing

### ISSUE THREAD

**Issue by sr320** [sr320/course-fish546-2018#45]
For this week you will `ssh` into `eagle.fish.washington.edu` and in the directory `/var/services/homes/fish546`  you will need to make a directory named your first name. In that new directory you will need to create a text document (you can call it anything you would like). In that text document you will need to provide the  answer to the following questions:

**A) What is the difference between nohup and tmux?
B) Which one would you be more likely to use and why?**

(_your user name and password will be provided in class today_)

Once completed, please come back here and comment with with word “success!” (Or feel free to ask questions)

**Comment by kimh11** [comment]
success!

**Comment by Jeremyfishb** [comment]
success, phew!

**Comment by wsano16** [comment]
success!

**Comment by yaaminiv** [comment]
success 🎉

**Comment by hgloiselle** [comment]
success

**Comment by kcribari** [comment]
success

**Comment by magobu** [comment]
success!

**Comment by laurahspencer** [comment]
success! 

FYI:  I ssh-d into eagle from my laptop but had the incorrect username (a couple times). I then tried with the real username and was told: 

`ssh_exchange_identification: Connection closed by remote host`  

Perhaps Eagle decided I was up to no good, and denied access from my IP.  (I accomplished the exercise by logging onto Eagle from mox).

**Comment by sr320** [comment]
@laurahspencer correct - after 3 failed attempts in a row, eagle blocks the IP

**Comment by jgardn92** [comment]
success

**Comment by calderatta** [comment]
success!

**Comment by grace-ac** [comment]
success!

**Comment by melodysyue** [comment]
success!
