### ISSUE TITLE
installing nano for GitBash

### ISSUE THREAD

**Issue by magobu** [sr320/course-fish546-2018#49]
I'm not able to use nano when using Git Bash from the ssh. I get the message `-sh: nano: command not found`
Any ideas on how to make this work or how to easily upload nano for Windows Git Bash?

**Comment by kubu4** [comment]
I think the issue you're encountering is dependent upon the system you're SSHing in to. If you're SSHing in to the server provided in class, it does not have nano, so that's why you get that error.

**Comment by magobu** [comment]
Thank you Sam! I thought we were supposed to use nano to answer the questions for week 5 quiz?? I'll check in class tomorrow 👍

**Comment by kubu4** [comment]
Hint: You don't have to use a text editor to put text in a file.

**Comment by magobu** [comment]
Thanks, I was able to get the assignment completed during class. I used Vim
instead.

*Marta Gomez-Buckley*
PhD Student
Fish Systematics and Biodiversity Lab
School of Aquatic and Fishery Sciences
University of Washington
Phone: 206 685-3438
