### ISSUE TITLE
Bowtie and GitHub Desktop Difficulties

### ISSUE THREAD

**Issue by hgloiselle** [sr320/course-fish546-2018#53]
I'm having problems with both Bowtie and Github Desktop. 

**Bowtie:**
I keep getting the following error:
Error reading _rstarts[] array: 6091976, 6092424

I'm doing research to try and resolve it, but I'm not sure I'll be able to figure it out before the rough draft release is due tonight.

**GitHub Desktop:**
I accidentally committed files that were too large to push, but now I can't get them out of the push queue and therefore am unable to commit anything new. I don't know how to fix this problem, but am continuing to try and figure it out.

**Rough Draft:**
Because of these problems, I'm not sure how much I'll be able to get to sync to GitHub that is new beyond the FastQC I've already done. For now I'll release what I have so far and continue to try and resolve my issues.

**Comment by kubu4** [comment]
> Bowtie:
I keep getting the following error:
Error reading _rstarts[] array: 6091976, 6092424

Can you please post screenshot (or link to Jupyter notebook) with code and subsequent error message?

> GitHub Desktop:
I accidentally committed files that were too large to push, but now I can't get them out of the push queue and therefore am unable to commit anything new. I don't know how to fix this problem, but am continuing to try and figure it out.

Via terminal:

1. Navigate to your git repo.

2. ```git rm --cache .```

3. Add files to your ```.gitignore``` file. This can be done via GitHub Desktop.

4. Add and commit all files in your git repo. This can be done via GitHub Desktop.

5. Push to GitHub.

**Comment by hgloiselle** [comment]
<img width="1108" alt="screen shot 2018-11-03 at 1 37 22 pm" src="https://user-images.githubusercontent.com/43651113/47957123-a0fa7d00-df6d-11e8-83e4-5b1a3be04b39.png">

I got this error when trying to code it multiple ways. This is the latest iteration that gives me the same error.

**Comment by kubu4** [comment]
Hmmm, I can't figure anything out.

However, I'd recommend using bowtie2 (http://bowtie-bio.sourceforge.net/bowtie2/index.shtml) or, better yet, hisat2 (https://ccb.jhu.edu/software/hisat2/index.shtml) instead of bowtie.
