### ISSUE TITLE
This week in progress

### ISSUE THREAD

**Issue by sr320** [sr320/course-fish546-2018#54]
What do you consider your primary accomplishment this week?

**Comment by kcribari** [comment]
My primary accomplishment was using find and xargs in place of complex for loops in order to do a command on 16 files. These commands eliminated a lot of frustration and made moving through the steps of my project much easier. I now have 16 txt files of clustered sequences that I will be working on blasting after one more round of cleaning.

**Comment by hgloiselle** [comment]
This week I was finally able to align my data with bowtie2 and successfully created a script to run on multiple files.

**Comment by yaaminiv** [comment]
This week I finished running `bismark` on Mox, identified DML and DMR in `methylKit`, and characterized locations of DML and DMR using `bedtools`. More details [here](https://yaaminiv.github.io/DML-Analysis-Part17/).

**Comment by calderatta** [comment]
This week I am in the process of running the perl script which parses each sequence read to a locus. This process is taking a while so I am in the process of getting access to Hyak to make this and future steps less daunting. I think my biggest accomplishment, however, was setting up a remote connection with my office computer to help split the load for now.

**Comment by wsano16** [comment]
This week, my primary accomplishment was figuring out how to best visualize my PCoA plots outside of Emporor and use ade4 to mark clusters in rStudio

**Comment by melodysyue** [comment]
This week, I figured out a way to blast sequences of my samples in an efficient way, that is, to create a combined unique sequence file and blast this file against NCBI. Use the resultant file with sequences and associated taxonomy as a reference database, and run through each of my samples against this created reference database.

**Comment by Jeremyfishb** [comment]
My primary accomplishment this week was getting eigenvectors calculated and plotted on ndms plots. This gave a list of proteins driving the differences observed between different treatment groups!

**Comment by jgardn92** [comment]
My primary accomplishment on my project this week was de-multiplexing my samples according the barcode file. Files are too big to upload to GitHub but they are on my computer and can now be used to filter by read number and construct a de novo genome.
My secondary accomplishment is not on my project, but the script I wrote for the quiz will be used to help automate downloading and organizing of large CT-scan files while eliminating the possibility of naming files incorrectly.

**Comment by laurahspencer** [comment]
I used transrate to get statistics on the gonad transcriptome assembly - check out my notebook entry: [transcriptome-assess-annotate.ipynb](https://github.com/fish546-2018/laura-quantseq/blob/master/notebooks/transcriptome-assess-annotate.ipynb) 

Also ran blast with the assembly, and installed required programs for quantseq trimming, etc. 
 Should have access to my quantseq data by Tuesday!  Hoping to do the processing on those files and align them with the transcriptome this week, but not sure if I need to re-assemble (would like some feedback on the tranrate results).

**Comment by magobu** [comment]
I am still working on homework for this week and trying to figure out if there is a way to get multiple files I have in .ab1 format to FASTQ format so I can open them without the need of Geneious. Still researching this.

I have gotten some information from Geneious support on how to get to run the data from project to do what I need. I am in the process of learning how to get the data I have in FASTQ uploaded to Geneious. 

My accomplishment for this week has been to stop getting frustrated by the lack of progress on project, but to realize that by the time I get to do my real data I know this much so far.

**Comment by grace-ac** [comment]
I think my biggest accomplishment was BLASTing on Mox and Hummingbird. I'm going to figure out how to use transrate to check my assembly (will look at laura's notebook post). 

Will get some basic stats on the assembly and some descriptive pie charts, etc. to be included on my poster for GSS.

**Comment by kimh11** [comment]
My biggest accomplishment was very modest. I finished indexing a reference genome using BWA on Mox. But, it was my first successful job on Mox!
