### ISSUE TITLE
Scripting

### ISSUE THREAD

**Issue by sr320** [sr320/course-fish546-2018#55]
Create either a script, jupyter notebook, or R markdown file that performs a relevant operation(s) on a number of files (>4) "automatically".

This should be in your class repo and should be written in a manner that when I clone the repo I can generate the output. 

For instance the files will need to be in the repo or the _script_ will need to be able to pull them from a public url. Note absolute paths will not work. 

please place the url to the script, jupyter notebook, or R markdown file below.

**Comment by kcribari** [comment]
[My Jupyter Notebook](http://localhost:8888/notebooks/Documents/Bioinformatics/GitHub/Cribari-eDNA/Jupyter_Notebooks/Scripting%20Issue%20%2355.ipynb)

**Comment by kcribari** [comment]
[Jupyter Notebook](https://github.com/fish546-2018/Cribari-eDNA/blob/master/Jupyter_Notebooks/Scripting%20Issue%20%2355.ipynb)

**Comment by hgloiselle** [comment]
[Jupyter notebook to run bowtie2](https://github.com/fish546-2018/hope-oyster2/blob/master/scripts/Scripting%20Issue%20-%20Downloading%20Data%20and%20Bowtie2.ipynb)

**Comment by yaaminiv** [comment]
[R Markdown file](
https://github.com/fish546-2018/yaamini-virginica/blob/master/analyses/2018-10-25-MethylKit/2018-10-25-MethylKit.Rmd) for running `methylKit`

**Comment by Jeremyfishb** [comment]
Week 6 quiz [script](https://github.com/Jeremyfishb/Jeremy-coral/blob/master/Week_6_quiz_script.md)

**Comment by calderatta** [comment]
week 6 quiz [repo](https://github.com/fish546-2018/calder-exon-capture/tree/master/week-6-quiz)

**Comment by wsano16** [comment]
week 6 quiz [Jupyter Notebook](https://github.com/fish546-2018/will-Chiru16S/blob/master/scripting-exercise/FastQC-scripting-exercise.ipynb)

**Comment by melodysyue** [comment]
week 6 quiz [script](https://github.com/fish546-2018/Yue-metabarcoding/blob/master/script/QC.sh)

**Comment by jgardn92** [comment]
My [script](https://github.com/fish546-2018/Jenny-Snailfish/blob/master/xFISH546/ScriptQuiz/ScriptHW.sh) which downloads a zipped filed containing two metadata files and an image stack, extracts variables from one of the metadata files, and then renames all the files in the image stack and rezips it. Script is not part of my class project but is needed for separate project

**Comment by laurahspencer** [comment]
[quiz script](https://github.com/fish546-2018/laura-quantseq/blob/master/scripts/scripting-quiz.sh)

Downloads files that match a certain pattern from Owl and creates a text file listing them - should clone the repo then execute script via:  bash scripts/scripting-quiz.sh

**Comment by grace-ac** [comment]
[jupyter notebook](https://github.com/fish546-2018/grace-Cbairdi-transcriptome/blob/master/notebooks/W6-scripting-quiz.ipynb)

**Comment by kimh11** [comment]
My [script](https://github.com/fish546-2018/hj-pangolin/blob/master/analyses/aligned-files/sam2bam-command.sh).

This creates a list of samtools commands to convert sam to bam files for all .sam files in the folder and writes them to another file.

The actual .sam files were too big to put on GitHub, so I created placeholder files with the same names. I will be running the scripts on Mox.
