### ISSUE TITLE
HTTP request sent, awaiting response

### ISSUE THREAD

**Issue by laurahspencer** [sr320/course-fish546-2018#58]
For the quiz this week i'm writing a script to download files from Owl, but only if they contain certain strings. I'm using wget and following a suggested script in the book: 

`wget --accept "201803_QuantSeq_Raw/CP-KS-Lib3-BC-[4-5][0-9][A-Z][A-Z]_S6_L008_R1_001.fastq.gz" --no-directories --recursive --no-parent \
http://owl.fish.washington.edu/wetgenes/201803_QuantSeq_Raw/ -P ../data/test-data/`

I'm testing the script, and I'm still "awaiting response" from Owl after ~15 minutes (and it's on the 2nd try). Is this an indication that Owl is rejecting my request? Current output: 

![image](https://user-images.githubusercontent.com/17264765/48295254-3c449400-e43f-11e8-9561-de3b6c33c6cc.png)

**Comment by kubu4** [comment]
It appears to be an issue with Owl.

Looks like it require a physical restart (i.e. power down, then power up using button on Owl).

**Comment by sr320** [comment]
will do

**Comment by kubu4** [comment]
Hold power button until unit beeps, then it will enter shutdown procedure. Same when powering on.

**Comment by sr320** [comment]
back online
