### ISSUE TITLE
converting ab1. files to FASQ

### ISSUE THREAD

**Issue by magobu** [sr320/course-fish546-2018#59]
Any one would know how to convert sequence files with .ab1 format to FASTQ? .ab1 files can be open with Geneious software, but I would like to be able to do some analysis using GitBash. Thanks

**Comment by sr320** [comment]
segret from emboss looks like a good option.
see https://www.biostars.org/p/309727/ for a couple of more that could be run through commandline..

**Comment by magobu** [comment]
Thanks Steven. I'll try that tomorrow!

*Marta Gomez-Buckley*
PhD Student
Fish Systematics and Biodiversity Lab
School of Aquatic and Fishery Sciences
University of Washington
Phone: 206 685-3438
