### ISSUE TITLE
Submitting an issue

### ISSUE THREAD

**Issue by sr320** [sr320/course-fish546-2018#63]
You can always submit an issue here if you are running into a hurdle. 
For this week’s project-progress grade you will need to post an issue regarding something you are trying to do for your project. 
Take some time to think about what information you need to provide. So someone could address the issue. For example you will need to provide access to data and code (if applicable). Or some subset.

Once you create said issue, provide a link to it here.

**Comment by hgloiselle** [comment]
my [issue](https://github.com/sr320/course-fish546-2018/issues/64)

**Comment by yaaminiv** [comment]
New issue: [isolate flanks created with `bedtools flank`](
https://github.com/sr320/course-fish546-2018/issues/66)

**Comment by calderatta** [comment]
Issue: [Completing job on MOX](https://github.com/sr320/course-fish546-2018/issues/68)

**Comment by kcribari** [comment]
Issue: [Homopolymers](https://github.com/sr320/course-fish546-2018/issues/70)

**Comment by grace-ac** [comment]
issue [blast nt](https://github.com/sr320/course-fish546-2018/issues/65)

**Comment by Jeremyfishb** [comment]
My [issue](https://github.com/sr320/course-fish546-2018/issues/72)

**Comment by wsano16** [comment]
[issue 🙍‍♂️  ](https://github.com/sr320/course-fish546-2018/issues/74)

**Comment by jgardn92** [comment]
Issue: [VMware virtual machine](https://github.com/sr320/course-fish546-2018/issues/75)

**Comment by kimh11** [comment]
My [issue](https://github.com/sr320/course-fish546-2018/issues/76).

**Comment by melodysyue** [comment]
My [issue about blast](https://github.com/sr320/course-fish546-2018/issues/77).

**Comment by laurahspencer** [comment]
[My issue](https://github.com/RobertsLab/resources/issues/494) about the isogroup designations. Still trouble shooting, so yet to close.

**Comment by magobu** [comment]
My [issue](https://github.com/fish546-2018/marta-eDNA/blob/master/HW_week7_Issue)

**Comment by magobu** [comment]
My [issue](https://github.com/sr320/course-fish546-2018/issues/87)
