### ISSUE TITLE
SAMtools mpileup 

### ISSUE THREAD

**Issue by hgloiselle** [sr320/course-fish546-2018#64]
When trying to run samtools mpileup, I keep only getting the help menu as an output. I also tried samtools sort, but ran into a similar issue. This is a link to the sample1.bam (url
http://eagle.fish.washington.edu/fish546/hope/sample1.bam) file that I'm trying to use. Below is an image of the code and error.
<img width="1115" alt="screen shot 2018-11-13 at 3 12 52 pm" src="https://user-images.githubusercontent.com/43651113/48449690-483e9780-e758-11e8-964e-980d8cbbaba4.png">

**Comment by kubu4** [comment]
Link to notebook?

**Comment by sr320** [comment]
@kubu4 thanks we got it - thanks (-o should be after file)
