### ISSUE TITLE
Completing job on MOX

### ISSUE THREAD

**Issue by calderatta** [sr320/course-fish546-2018#68]
I've been running a published custom perl script to parse reads into targeted genes. This uses blastn and is taking a while (almost a week so far), so I'm trying to get access to Hyak. Meanwhile, it would be great if I could get help to run the remainder of this job on MOX from someone with access. There's a [directory](https://github.com/fish546-2018/calder-exon-capture/tree/master/preads-script) in my [repo](https://github.com/fish546-2018/calder-exon-capture) with the script to run. All commands are local.

**Comment by sr320** [comment]
@kubu4 do you think you could get this going on mox?

**Comment by sr320** [comment]
admittedly am not readily finding the actual perl script- though it is stated it is in the zip file.

**Comment by kubu4** [comment]
Yeah, we'll need more info on this...

**Comment by kubu4** [comment]
Well, actually, I think I see what's happening. Give me a sec...

**Comment by kubu4** [comment]
Looking at this, it will likely go faster if he adds the ```-num_threads n``` option to line 64 of the ```band.pl``` file. Currently, it's not set, so I think ```blast``` defaults to one thread.

Regardless, I'll get this running on Mox shortly.

**Comment by kubu4** [comment]
Up and running here:

```/gscratch/srlab/calder_exon_capture```

**Comment by sr320** [comment]
Thanks!

**Comment by calderatta** [comment]
Thank you to both of you. Let me know if you need more info.

**Comment by kubu4** [comment]
That blast job finished (received email, no errors). Haven't looked at
SLURM file for any errors.

**Comment by sr320** [comment]
Here is the resulting files
http://gannet.fish.washington.edu/seashell/bu-mox/calder_exon_capture/

**Comment by sr320** [comment]
And for reference - this is how @kubu4 ran it on mox.

```
#!/bin/bash
## Job Name
#SBATCH --job-name=calder_blast
## Allocation Definition 
#SBATCH --account=srlab
#SBATCH --partition=srlab
## Resources
## Nodes (We only get 1, so this is fixed)
#SBATCH --nodes=1
## Walltime (days-hours:minutes:seconds format)
#SBATCH --time=30-0:00:10
## Memory per node
#SBATCH --mem=120
##turn on e-mail notification
#SBATCH --mail-type=ALL
#SBATCH --mail-user=samwhite@uw.edu
## Specify the working directory for this job
#SBATCH --workdir=/gscratch/srlab/calder_exon_capture

# Add BLAST to system PATH
export PATH=$PATH:/gscratch/srlab/programs/ncbi-blast-2.6.0+/bin

# Run Calder's script (modified - removed curl and unzip commands from original version)
bash main.sh
```

**Comment by calderatta** [comment]
While looking into the Trinity [issue](https://github.com/sr320/course-fish546-2018/issues/81), the problem looks like it might be coming from this step. The `band.pl` file is out of date. Can I ask for help to run this again but with the updated [version](https://github.com/fish546-2018/calder-exon-capture/blob/master/preads-script/bandp.pl)?

**Comment by kubu4** [comment]
Submitted this to CoEnv node, but the job has been queued, as someone is currently using the two CoEnv nodes (they've been running for 3.5 days already, so hopefully they finish soon).

Set max runtime as two days, to try to avoid conflict with scheduled downtime on 12/11/2018. However, might be moot if that other job takes too long. Regardless, I'll post here when job starts and ends.

Working directory is set as: 

```
/gscratch/srlab/calder_exon_capture/20181205
```

Here's SBATCH script used to run job:

```
#!/bin/bash
## Job Name
#SBATCH --job-name=calder_blast
## Allocation Definition 
#SBATCH --account=coenv
#SBATCH --partition=coenv
## Resources
## Nodes
#SBATCH --nodes=1
## Walltime (days-hours:minutes:seconds format)
#SBATCH --time=02-0:00:10
## Memory per node
#SBATCH --mem=120
##turn on e-mail notification
#SBATCH --mail-type=ALL
#SBATCH --mail-user=samwhite@uw.edu
## Specify the working directory for this job
#SBATCH --workdir=/gscratch/srlab/calder_exon_capture/20181205

# Add BLAST to system PATH
export PATH=$PATH:/gscratch/srlab/programs/ncbi-blast-2.6.0+/bin

## All input files and scripts were downloaded and unzipped using following commands:
## curl http://eagle.fish.washington.edu/fish546/calder/preads/preads-data.zip > preads-data.zip
## unzip preads-data.zip

# Edit band.pl file to run blastn with 28 threads
# Uses sed pattern matching to find line with blastn command.
# Then uses sed substitute command to find -outfmt 6 and replace.
sed -i '/blastn/ s/-outfmt 6/-outfmt 6 -num_threads 28/' bandp.pl

# Run Calder's script (modified - removed curl and unzip commands from original version)
bash main.sh
```

**Comment by kubu4** [comment]
Also, @calderatta, you should update your project zip file to include the updated Perl script. I didn't realize it hadn't been updated until just now - not sure what made me double check that...

Anyway, I replaced it with [Commit 6f881a0](https://github.com/fish546-2018/calder-exon-capture/commit/6f881a02ca3efc4bfb324151807d80fc301c19bd) and it will use that version when the job actually runs.

**Comment by kubu4** [comment]
@calderatta Job just failed because there wasn't a file called ```main.sh``` to run. Didn't realize it, as I just downloaded and unzipped that previous file. Where does ```main.sh``` live so I can run it?

**Comment by kubu4** [comment]
Never mind, found it. However, job's failing to execute because there's a Perl module that the script requires that we don't have installed (line 28 of the script - Parallel ForkManager). I'll see if I can get it installed.

**Comment by kubu4** [comment]
Ok, got that module installed and the job is running!

**Comment by calderatta** [comment]
Thanks Sam. Looks like that module was added in the updated version, but glad it's running.

**Comment by kubu4** [comment]
Job finished with the proper exit code, but a glance at the slum output file makes me wonder if the job ran properly.

![image](https://user-images.githubusercontent.com/4514104/49691008-94c68a00-faee-11e8-8d52-1f2654ce52b8.png)
