### ISSUE TITLE
Oyster genes for bedtools intersect

### ISSUE THREAD

**Issue by hgloiselle** [sr320/course-fish546-2018#69]
I'm hoping to use bedtools intersect in order to see if the SNPs I identified are located in gene regions. I was wondering what to use as a reference for the location of the genes

**Comment by sr320** [comment]
Here is track to compare with you SNPs using bedtools intersect
`http://owl.fish.washington.edu/halfshell/genomic-databank/Olurida_v081.all.sorted.gff`

(Details on how it was made: http://onsnetwork.org/kubu4/2018/08/08/genome-annoation-olympia-oyster-genome-annotation-results-02/)
