### ISSUE TITLE
Project Ideas

### ISSUE THREAD

**Issue by sr320** [sr320/course-fish546-2018#7]
As I mentioned, each student will have a "project" that results in a "product". Do you have any preference to what such project is involved with? What is one idea that comes to mind based on the reading and your interests. Please include any questions or concerns.

**Comment by magobu** [comment]
I am assuming that this is going to be a project that is completed at the end of the quarter, or could it be a section of a larger project?

I Have some data from a pilot study that I could use. My research focuses on **what is there** rather than the **what it does**. One section of my research would be to determining how similar or different three sympatric cryptobenthic fishes are from each other, with the end goal of deciphering if they are three different species even though they are part of the in the same  _Eviota_ genus complex/clade. 

I also will try to do something related to eDNA analysis, since I'll be doing my own sampling on December. I'll try to get my hands on some mock data I could borrow from the SMEA group I'm in contact with.

**Comment by yaaminiv** [comment]
For my project, I'll characterize differentially methylated regions (DMRs) between Eastern oysters exposed to high pCO2 conditions, and those exposed to ambient pCO2 conditions. My final product will be a list of DMRs, associated genes, and gene functions.

**Comment by jgardn92** [comment]
For my project I would like to work with raw RADSeq data from relatively distantly related species and be able to align and filter SNPs. The data will be from 45 species in the family of snailfishes Liparidae. My final product will be a phylogenetic tree for the family.

**Comment by grace-ac** [comment]
I would like to practice and work with some transcriptomic data. That way, once the crab transcriptome data comes in, I'll have a head start in having a better understanding of the process, as well as a workflow/pipeline started.

**Comment by Jeremyfishb** [comment]
I will be examining differential protein expression between coral tissue and skeletal material in bleached and non-bleached corals. I have run the mass-spec on the samples already, and my collaborators have done some stuff to the data but I am not sure what they have done, why they have done it, and don't yet know how to process any of the data we have or what it means. I'm hoping that this class will help me to be able to do everything I need to organize, document, process and interpret these data independently.

**Comment by calderatta** [comment]
I would like to work with exon-capture data and produce a phylogeny as my output. This process will be a part of my thesis work on pleuronectids, however I am not expecting to have those data for at least one month. For now I am going to use sequence data from another project and try to develop a reproducible script to use on my samples, but I if I can get my pleuronectid sequences quickly, I will use those for the project.

**Comment by zscooper** [comment]
I'm currently working on a project on comparative microbial diversity and community structure between different subfreezing, hypersaline environments in the Arctic as a chapter of my thesis. This project has 22 samples of 16S amplicon data from discreet time points and locations. I'd like to polish up the results from my project over this quarter and get it to a publishable product.

**Comment by wsano16** [comment]
I would like to use the structure of this class to begin work with 16S amplicon sequence data from archived elephant scat samples. It will be a good opportunity to work on QC methods in bioinformatics, since many of the samples are very old and likely degraded. I will compare elephant microbiomes by PCoA to tease out relationships between microbiome structure, sample age, sample origin, and elephant species. My product will likely take the form of a comprehensive diversity analysis.

**Comment by hgloiselle** [comment]
I do not have any of my own data at the moment so my main goal with the project is to practice what I hope to eventually do which is investigate population structure and diversity of certain species that humans relied on for subsistence in the past. In the future I will work with both modern and ancient DNA, but for this class I will use modern genomic data until I become more experienced using bioinformatic methods. Admittedly I’m still not 100% sure what I want to do for this project and I’m poking around looking for data to use and may ask my former advisor for a data set I can practice on.

**Comment by laurahspencer** [comment]
I want to learn how to process RNA sequence data with the end goal of differential expression analysis between my oyster groups.  The samples I sent Katherine are listed on the bottom of this [GitHub issue](https://github.com/RobertsLab/project-olympia.oyster-genomic/issues/34#event-1497598684):  

My samples' QuantSeq data is delayed a few weeks, so Katherine is sending me a couple things I can play with to learn and develop pipelines:  
  - Raw RNA full transcriptomic data that was sequenced with the first few gonad samples I sent her. I can use this data to learn how to assemble a transcriptome, which I can use in my mapping step. She is also assembling using the same data, so I could just use hers once it's ready.  
  - Raw RNA QuantSeq data from her projects to learn how to demultiplex, map, QA/QC, quantify, differential expression .  

Katherine also offered to send me her assembled transcriptome.  I have no idea how much time it will take for me to do the above, so interested in your assessment of what's feasible and makes most sense.

**Comment by kimh11** [comment]
I would like to work with whole genome sequence data of ~ 10 samples from two species of pangolins and create a reproducible pipeline for aligning to a reference genome, calling SNPs, and design primers for amplicon sequencing. My main goal would be to make a robust and reproducible pipeline that I can easily re-run as I collect more data.

**Comment by kcribari** [comment]
I will most likely be using data that is ready to go, and then applying what I learned to my thesis data once its ready. But I will be taking data from a NextGen sequencing run and using Bioinformatics to cluster the reads based on similarities to investigates the community structures at each of the sampling locations given biological replicates and environmental factors.

**Comment by melodysyue** [comment]
For my project, I will be working with microbiome data (16S) and metabarcoding data for diet analysis (12S) along with environmental/sampling information. I would like to set up a pipeline to filter, merge, demultiplex, dereplicate and classify these sequences and generate a summary output file.
