### ISSUE TITLE
Looking for Unknown Pattern In Sequence

### ISSUE THREAD

**Issue by kcribari** [sr320/course-fish546-2018#70]
I was tasked with finding homopolymers in my sequences and from what I could find online the command to do this is: 

`!for filename in /Users/kellycribari/Documents/Bioinformatics/GitHub/Cribari-eDNA/Cluster/NOSP*.txt; do \
  echo $filename | \
  grep -E '([A-Z])\1*'\
; done`

Is this the correct grep command for finding long strings of a single base pair in a sequence? This code did not work because of invalid syntax but I'm not sure what about it is incorrect.

**Comment by kubu4** [comment]
It would be helpful to see the actual error message; it might provide a clue as to which part has the incorrect syntax.

Also, can you please describe what pattern you're trying to find in your files?

Do you have a link to your Jupyter Notebook you could share?

With that being said, I'd try changing to this:

```for filename in /Users/kellycribari/Documents/Bioinformatics/GitHub/Cribari-eDNA/Cluster/NOSP*.txt; do grep -E '([A-Z])\1*' "${filename}"; done```

The first problem I noticed with your initial attempt was the ```echo $filename``` part. That will print the name of the file and then pass that _string_ to the ```grep``` command. As such, I don't think ```grep``` sees that as an actual file to work on. I've removed the ```echo``` command and put the variable, ```"${filename}"``` at the end of the ```grep``` command (which is where it would normally go).

I've also removed the backslashes, as they were confusing to read in this format. I presume they were intended as line continuations for you Jupyter Notebook (to make it easier to read there)?

**Comment by sr320** [comment]
If you are just looking for strings of A, C, G, or Ts, 
this jupyter notebook shows how to do this crudely with grep. 
https://github.com/fish546-2018/Cribari-eDNA/blob/master/Jupyter_Notebooks/01-SR-homopolymer.ipynb

Note if you run it locally the strings will be colored for easy visualization.

**Comment by sr320** [comment]
Added a more simple grep in the notebook linked above.
```
!grep --color -e AAAAAAA -e CCCCCCC -e TTTTTTT -e GGGGGGG \
../Cluster/NOS*fasta | wc -l
```
