### ISSUE TITLE
creating a bash script

### ISSUE THREAD

**Issue by Jeremyfishb** [sr320/course-fish546-2018#72]
I still don't understand how to save a bash script. If I put a header and some commands like this:

**#!/bin/bash
set -e
set -u
set -u pipefail
some_command some_file > output_destination**

Then what do I need to do to name it and make it save as a bash script?

Also, will it be saved in the directory where I created it? Or do I need to specify where I want it saved?

**Comment by sr320** [comment]
It is just a text file, 
Use your gui text editor to create and save where you would like. 

example - https://d.pr/f/O3yTH5

**Comment by Jeremyfishb** [comment]
I see, I just tried it and copied and pasted the text into gitbash and it worked. But how do you get the text file to end with the .sh suffix?

**Comment by sr320** [comment]
see
https://d.pr/i/JIL67f
