### ISSUE TITLE
Intricacies of for loops in jupyter notebook

### ISSUE THREAD

**Issue by laurahspencer** [sr320/course-fish546-2018#73]
I'm running for loops in a Jupyter Notebook using bash and have encountered a couple issues: 

1. Can't figure out how to redirect the output to a text file. I've tried the suggestions listed in this [stackoverflow post](https://stackoverflow.com/questions/18612603/redirecting-output-of-bash-for-loop), but none have successfully worked. Here's an example of my attempt - also tried `>> out.txt` inside the loop before `done`. 

![image](https://user-images.githubusercontent.com/17264765/48651743-23912c80-e9b1-11e8-8d00-4233b1651640.png)

2. A variable I set outside the loop (path to a program) isn't working inside the loop

![image](https://user-images.githubusercontent.com/17264765/48651838-8b477780-e9b1-11e8-9c39-e8fae156d6ef.png)

**Comment by sr320** [comment]
1. I think you want to write out standard error prior to `done`

`2> $file.err`

2. does not seem to be an impediment? 

If you post jupyter nb on github I can troubleshoot.

**Comment by kubu4** [comment]
1. What @sr320 said.

2. Agree with @sr320 . Also, I don't see that variable defined in that cell. Is it defined earlier in the notebook? Note, @yaaminiv had/has an issue with using variables defined outside of her current cell (https://github.com/RobertsLab/resources/issues/488#issuecomment-439194085) as well.

**Comment by laurahspencer** [comment]
1. This is what worked (outside of loop): 
`done >> bowtieout.txt 2>&1`

2. Not an impediment, just annoying. The variable defined previously works between cells, but not within the loop. Oh well!
