### ISSUE TITLE
Embedding 3d plots in Jupyter

### ISSUE THREAD

**Issue by wsano16** [sr320/course-fish546-2018#74]
Does anyone have experience embedding Emperor plots in Jupyter notebooks? It looks like there used to be a tutorial [here](http://emperor.microbio.me/uno/build/html/examples.html#in-the-jupyter-notebook), but now it is gone. I'd like to create an interactive feature that lets you cycle between multiple 3d plots.

**Comment by sr320** [comment]
It would appear this will work in Jupyter and the instructions you link to seem to be good?
http://emperor.microbio.me/uno/build/html/examples.html#in-the-jupyter-notebook
