### ISSUE TITLE
Virtual Machine out of Space VMware

### ISSUE THREAD

**Issue by jgardn92** [sr320/course-fish546-2018#75]
Last week I ran into an issue where the VMware virtual machine I'm using to run Ubuntu ran low on disk space (18.3 GB out of 20 GB allotted). I immediately stopped, moved everything off of the virtual machine and then ran the defragment and compress options from the virtual machine settings. I haven't received another disk space low error but it still appears that the disk space being occupied by my virtual machine is the same as before.
Am I just misunderstanding how the virtual machine uses disk space?

**Comment by kubu4** [comment]
Hmmm, this is probably more complicated than we're able to deal with. My first thought is create a virtual machine with more disk space. The thing is that the virtual machine needs some minimum amount of disk space just for the operating system. Knowing that, 20GB seems rather small to me, particularly if you want to actually put any additional programs/files on it.

**Comment by kubu4** [comment]
Did you resolve this? If yes, how?

**Comment by jgardn92** [comment]
I'm not entirely sure if I actually resolved it but more found a workaround that seems to be working. I moved everything off my VM and then disabled sharing folders. Instead I've been working off an external hard drive that I connect to the VM and the host alternatively. The VM still seems to occupying the same space on my disk but it's not running out of space anymore as far as I can tell.
