### ISSUE TITLE
Figuring out progress of BWA runs

### ISSUE THREAD

**Issue by kimh11** [sr320/course-fish546-2018#76]
My [BWA job](https://github.com/fish546-2018/hj-pangolin/blob/master/scripts/runbwa.slurm) failed on Mox because it couldn't be complete in the 5 hours I requested. 

The last 50 lines of the slum.out file is [here](https://github.com/fish546-2018/hj-pangolin/blob/master/analyses/bwa-output.txt). Is there any information in here that I can use to figure out how much longer I should've requested. 

For now, I've learnt my lesson and requested way more time. 😄

**Comment by kubu4** [comment]
Request something like 20 days. There's almost no downside to requesting a
ridiculously long period of time for a job.

**Comment by kimh11** [comment]
Thank you!
