### ISSUE TITLE
Extract all the hits with the 100% match from the blast result

### ISSUE THREAD

**Issue by melodysyue** [sr320/course-fish546-2018#77]
My barcode has limited resolution, I would like to take a look at all hits with 100% match from the blast result (via blastn?). How should I do this? Thanks!

**Comment by sr320** [comment]
This issue needs more details.
Is blast complete? If so provide the blast result so someone could inspect and offer advice. 
What is the "match" - specifically what is the database and what is the query?

If you have not completed the blast job - what would you like to be the query and database?
