### ISSUE TITLE
Final Stretch

### ISSUE THREAD

**Issue by sr320** [sr320/course-fish546-2018#79]
Yesterday's  [video](https://washington.zoom.us/recording/play/L4SheRPSE3t153xTqBU_F8H9Kv_O8F34YYLtmj8YYz0BGnLL8_vv292TZbXuTae9?continueMode=true) is up. 

We decided on the project grading rubric.
![img_1136](http://gannet.fish.washington.edu/seashell/snaps/IMG_1136.JPG_2018-11-21_10-47-59.png)

Everyone will give a presentation during week 10. That presentation would be found in your repo. 

25% 1. What is your question?
25% 2. What did you do with your data?
25% 3. A Visualization of what you did
25% 4. Next Steps

You will also be making a new release.

Feel free to ask question below. Next week (Week 9) we will be focusing on visualization.

No questions this week! Please use this time to make up any missing assignments - see the [gradebook](https://catalyst.uw.edu/gradebook/sr320/104455)

**Comment by laurahspencer** [comment]
Clarification request:  will we be presenting our results tomorrow (Tuesday), or Thursday?

**Comment by sr320** [comment]
Primarily Thursday unless anyone needs to present today.
