### ISSUE TITLE
Creating a Repository

### ISSUE THREAD

**Issue by sr320** [sr320/course-fish546-2018#8]
Please go to https://github.com/fish546-2018 and “Create a New Repository”.  Please name the repository [firstname]-[oneword]. Adding a Readme file. In theory the one word would be associated with your project.

See [this example](https://d.pr/i/HgVft4)

**Comment by yaaminiv** [comment]
My [class repo](https://github.com/fish546-2018/yaamini-virginica)

**Comment by kcribari** [comment]
My eDNA [repository](https://github.com/fish546-2018/Cribari-eDNA)

**Comment by kimh11** [comment]
My class [repo](https://github.com/fish546-2018/hj-pangolin)

**Comment by wsano16** [comment]
[My class repo](https://github.com/fish546-2018/will-NEWA)

**Comment by grace-ac** [comment]
My [class repo](https://github.com/fish546-2018/grace-transcriptome)

**Comment by laurahspencer** [comment]
Laura's [repo](https://github.com/fish546-2018/laura-quantseq)

**Comment by magobu** [comment]
Mi [repositorio](https://github.com/fish546-2018/marta-sigillata)

**Comment by Jeremyfishb** [comment]
My [repository](https://github.com/Jeremyfishb/Jeremy-coral.git)

**Comment by shellywanamaker** [comment]
my [repo](https://github.com/shellytrigg/Shelly_Pgenerosa)

**Comment by zscooper** [comment]
my [repo](https://github.com/fish546-2018/zac-cryobac)

**Comment by shellywanamaker** [comment]
I created my repository in under my account instead of FISH546 (https://github.com/fish546-2018). How can I share my repo with FISH546? Forking?

**Comment by sr320** [comment]
@shellytrigg 
> I created my repository in under my account instead of FISH546 (https://github.com/fish546-2018). How can I share my repo with FISH546? Forking?

I do not think so, I would create a new repo in FISH546 and simply put a link in the Readme.md to your other repo

Or you could delete the one in your account, and create a new one....

**Comment by melodysyue** [comment]
My [metabarcoding repo](https://github.com/fish546-2018/Yue-metabarcoding/blob/master/README.md)

**Comment by calderatta** [comment]
my [exon capture repo](https://github.com/fish546-2018/calder-exon-capture)

**Comment by jgardn92** [comment]
my [repo](https://github.com/fish546-2018/Jenny-Snailfish)

**Comment by hgloiselle** [comment]
my [repo](https://github.com/fish546-2018/hope-whales)
