### ISSUE TITLE
Readme updates

### ISSUE THREAD

**Issue by sr320** [sr320/course-fish546-2018#82]
For this week lets pay a bit of attention to your repo readme. 

Be sure to update this with an eye toward the final project. 
Make sure the 4 items in the [project rubric](https://github.com/sr320/course-fish546-2018/issues/79) are clearly evident in your readme. 
Please provide a link to your readme below.

**Comment by yaaminiv** [comment]
[Updated repo README.md](https://github.com/fish546-2018/yaamini-virginica/blob/master/README.md). I don't have final results there (yet), but the structure will remain the same.

**Comment by hgloiselle** [comment]
updated [readme](https://github.com/fish546-2018/hope-oyster2/blob/master/README.md)

**Comment by grace-ac** [comment]
current version of updated [repo README.md](https://github.com/fish546-2018/grace-Cbairdi-transcriptome/blob/master/README.md)

Work in progress, but overall outline is there.

**Comment by wsano16** [comment]
[readme](https://github.com/fish546-2018/will-Chiru16S/blob/master/README.md)
pending final results and workflow, this will be my final readme.md

**Comment by Jeremyfishb** [comment]
my [readme](https://github.com/Jeremyfishb/Jeremy-coral/blob/master/README.md). Like others, it's still in the outline phase...

**Comment by kimh11** [comment]
My [readme](https://github.com/fish546-2018/hj-pangolin/blob/master/README.md).

It will hopefully be updated with some visualizations in the next day or so.

**Comment by jgardn92** [comment]
Updated [readme](https://github.com/fish546-2018/Jenny-Snailfish/blob/master/README.md), pending final results.

**Comment by laurahspencer** [comment]
My [readme](https://github.com/fish546-2018/laura-quantseq/blob/master/README.md) - I'll clean things up a bit before final release

**Comment by melodysyue** [comment]
My [readme](https://github.com/fish546-2018/Yue-metabarcoding/blob/master/README.md)
