### ISSUE TITLE
Visualize the process

### ISSUE THREAD

**Issue by sr320** [sr320/course-fish546-2018#83]
What would be a good visual representation of your process?

**Comment by yaaminiv** [comment]
I think a flowchart would be a good visual representation of my process. I could include a box for each step (i.e. program or command) and either explain or have a small visual that explains how the sequence data is treated at each step.

**Comment by grace-ac** [comment]
I like Yaamini's idea and also think creating a flow chart of my process would be easy to follow. Would include the assembly process, BLAST, using BLAST results to create the different visual/graphical products.

**Comment by hgloiselle** [comment]
I will create a flowchart of the different steps I used to get to the final product. I think it would be an effective method for conveying the process and will be useful in the future when I go back and use my own data.

**Comment by kcribari** [comment]
I will be creating a flow chart that shows the steps I took to clean the data and split one raw sequencing file into many clustered and blasted sequence files, throughout those steps.

**Comment by melodysyue** [comment]
I like the idea of the flow chart. I think I will be using flow chart to explain the process as well. I also like to show the remaining number of reads after each filtering step.

**Comment by kimh11** [comment]
I'm also stealing Yaamini's idea of flow charts. I will make a flow chart that shows each of the steps from fastq files to vcf files. For steps that do have an intermediate file I'll show that in a figure form.

**Comment by wsano16** [comment]
I will be using a flow chart based on the `provenance` feature built into QIIME2, which traces all analyses and visualizations back through the data processing steps to the raw input files.

**Comment by calderatta** [comment]
I will also be doing a flow chart for my process. I can show the full workflow, then go through each step in more detail, adding helpful visuals such as the FastQC output.

**Comment by magobu** [comment]
I will use also a flow chart to represent the process, with an emphasis on the different detours and "bumps in the road" I encounter through this learning journey.

**Comment by Jeremyfishb** [comment]
My representation will also be kind of like a flow chart that will go through the steps I've made to reach where I am at in my analysis.

**Comment by laurahspencer** [comment]
Not surprisingly ... flow chart!  I'll visualize the two parallel processes of 1) assembling a transcriptome and 2) deriving / processing quantseq data, then they will merge into the count/analysis/visualize process.

**Comment by jgardn92** [comment]
A flow chart showing how the stacks process works will be my process visualization
