### ISSUE TITLE
Visualize the end

### ISSUE THREAD

**Issue by sr320** [sr320/course-fish546-2018#84]
What would be an appropriate visual representation of your findings / product?

**Comment by yaaminiv** [comment]
There are a few visual representations I have in mind:

- Plots depicting observed vs. expected CpGs methylated
- Venn diagram depicting gene annotations for DMRs in control and treatment oysters
- Histograms showing where the closest, non-overlapping DMR was for mRNA coding regions

I also have a handful of tables with information about DMR location with respect to mRNA coding regions, exons, and introns that may or may not lend themselves to other visuals.

**Comment by grace-ac** [comment]
- graphical representations (pie charts... not sure what else....) of the breakdown of interesting GO terms and GO slim terms
- word cloud (i'll make my own) of blast with nt database to find taxonomy 
- tables of interesting stats from transcriptome assembly
- maybe a venn diagram looking at homologs between and different from crab transcriptome and others...?

**Comment by kcribari** [comment]
My visual presentation would be a heat map of the abundance of sequences for given taxa by sample, which would be shown as location. For the overall presentation, I plan to also include a map to give spatial orientation to my samples and a flowchart to represent the data cleaning process.

**Comment by hgloiselle** [comment]
I'm going to be using IGV in order to visualize where in the genome the SNPs occur. I will compare the locations of the SNPs for both samples in relation to the reference genome

**Comment by melodysyue** [comment]
* Pie chart showing the relative abundance of different prey species; 
* Heat map showing the frequency of occurance of different prey species; 
* a map showing the sample location; 
* some visualization showing the ties of the blast results. Since my fragment is short, it does not have very good taxonomic resolution for certain species.

**Comment by wsano16** [comment]
- taxa relative abundance barplots
- summary barplots for each region
- EMPeror plots to visualize beta diversity metrics (Bray Curtis, (Un)weighted UniFrac) by ASVs 
- Differential abundance plots
- Summary PICRUSt output to communicate functional potential of sampled microbiomes

**Comment by calderatta** [comment]
I'm not exactly sure what the final output will be yet. I was hoping to get some aligned reads, but that's not looking like that will be the case. The main issue being that my reads are not aligning to their references genes. But I think there are still some interesting relationships I can still visually like histograms and pie charts showing read size and number, and how many reads were able to align.

**Comment by kimh11** [comment]
My final product will be a .vcf file of 10 individuals from 2 species. I will use IGV to visualize a subset of the interesting SNPs. I am also looking into other ways to visualize SNPs such as CircosVCF but not sure if it will work without karyotypes.

**Comment by magobu** [comment]
I am working on getting three main visuals for my project:
1. The map of the area sampled
2. A flow chart of the data analysis process (highlighting the steps I was able to accomplish)
3. Probably a simple graph to show the scale of the data (from total to the subset I was working with)
4. If I get to do a crude blast of a subset of the non-finalized data, a visualization of the taxa present using some of the tools in Galaxy

**Comment by Jeremyfishb** [comment]
I will show a venn diagram with the number of proteins found in each coral treatment group and the number of proteins shared between each combination of treatment groups. Also I will show an NMDS plot with clustering and a subset of eigenvectors representing significant proteins that influence the grouping.

**Comment by laurahspencer** [comment]
I will have PCA biplots with my gonad and larval quantseq data, in addition to some scatter plots showing counts of genes that are "significantly" different between pH groups (quotes used b/c bonferroni correction wipes out any significance ... interested in discussing this with folks in class).

**Comment by jgardn92** [comment]
I will have barplots representing sample coverage as well as maybe an IGV type visualization of where the snps are occurring in the catalog (de novo genome).
