### ISSUE TITLE
Missing assignments

### ISSUE THREAD

**Issue by sr320** [sr320/course-fish546-2018#85]
Do you have any missing assignments?
(yes or no)

**Comment by magobu** [comment]
Yes :(

**Comment by yaaminiv** [comment]
no 🎉

**Comment by Jeremyfishb** [comment]
Nope

**Comment by grace-ac** [comment]
yes

**Comment by jgardn92** [comment]
No

**Comment by kcribari** [comment]
No

**Comment by hgloiselle** [comment]
yes. this is the [release](https://github.com/fish546-2018/hope-oyster2/releases/tag/v1) for my project draft. I didn't realize the original release was deleted when I had to delete and re-upload my repo

**Comment by melodysyue** [comment]
Nope. But I have one late assignment:(

**Comment by wsano16** [comment]
Nope

**Comment by calderatta** [comment]
no

**Comment by kimh11** [comment]
No (not anymore 😄)

**Comment by laurahspencer** [comment]
Yes, still need to update my readme file. 
After that I should be all clear.
