### ISSUE TITLE
Stacks `tsv2bam` error

### ISSUE THREAD

**Issue by jgardn92** [sr320/course-fish546-2018#88]
I am running into issues with the Stacks program and the command `tsv2bam`.
From the stacks [documentation](http://catchenlab.life.illinois.edu/stacks/comp/tsv2bam.php) I believe I am running the command correctly. Below is an example running just one sample but the error is the same when I try to run all samples.
`tsv2bam -P ./stacks/ -s Lflorae666-cap`
`tsv2bam: src/tsv2bam.cc:247: void run(const std::vector<int>&, const string&, const std::unordered_map<int, long unsigned int>&, std::size_t, std::ostream&): Assertion ``sloc->len <= cloc_len' failed.`
`bash: line 1: 34659 Aborted                 (core dumped) tsv2bam -P ./stacks/ -s Lflorae666-cap`

**Comment by kubu4** [comment]
Hmmm, Stacks is a tricky one, due to the numerous steps involved. Any reason you're not running the semi-automated pipeline (i.e. ```denovo_map.pl```)?

What were your commands for the preceding steps?

- ```ustacks```

- ```cstacks```

- ```sstacks```

Do you have log files from each of these steps available for viewing?

**Comment by jgardn92** [comment]
I was trying to go through the pipeline step by step in the hopes of understanding how it works better. Additionally, I didn't have a population map file but I have since made one so I think I am going to attempt running the `denovo_map.pl` next to see if it can fix it.  
For all three commands I didn't get a log file but I did save them as jupyter notebooks:  
- `ustacks`[command](https://github.com/fish546-2018/Jenny-Snailfish/blob/master/notebooks/Ingrid-runfiles/run_ustacks_jg.sh) and [notebook](https://github.com/fish546-2018/Jenny-Snailfish/blob/master/notebooks/ustacksRun.ipynb)  
- `cstacks`[command](https://github.com/fish546-2018/Jenny-Snailfish/blob/master/notebooks/Ingrid-runfiles/run_cstacks_jg.sh) and [notebook](https://github.com/fish546-2018/Jenny-Snailfish/blob/master/notebooks/cstacksRun.ipynb)  
- `sstacks` [command](https://github.com/fish546-2018/Jenny-Snailfish/blob/master/notebooks/Ingrid-runfiles/run_sstacks_jg.sh) and [notebook](https://github.com/fish546-2018/Jenny-Snailfish/blob/master/notebooks/sstacksRun.ipynb)

**Comment by jgardn92** [comment]
I ran a subset of the samples through the `denovo_map.pl` and they works so long as I disabled gapped alignments for `ccstacks` and `sstacks`. So still not sure why `tsv2bam` was failing when trying to run it on it's own. The call from the log file for the `denovo_map.pl` was identical to what I was trying to run by hand.
