### ISSUE TITLE
End-of-class Happy Hour

### ISSUE THREAD

**Issue by yaaminiv** [sr320/course-fish546-2018#90]
There was some discussion of having an end-of-class happy hour next week + trying to find a way for all of us to stay connected as we do more bioinformatics research! Step 1 is to have a happy hour next week...so here's a Github issue for scheduling.

Respond to this issue with 💯 for HH on Tuesday, 🎉 for HH on Thursday. Include any time restrictions you may have.

**Comment by laurahspencer** [comment]
:tada: 
After 5ish for me

**Comment by hgloiselle** [comment]
💯🎉 either day and any time is good with me

**Comment by kimh11** [comment]
💯 🎉 No time restrictions for me

Yay for a happy hour!

**Comment by grace-ac** [comment]
🎉  ! 
No time restrictions

**Comment by calderatta** [comment]
💯 maybe if later in the day, but likely not going to be free either day.

**Comment by jgardn92** [comment]
💯 🎉!  
Great idea Yaamini!!

**Comment by melodysyue** [comment]
💯 🎉 ! No time restriction:)

**Comment by yaaminiv** [comment]
Let's do Thursday 5 p.m. at College Inn. Our first agenda item can be figuring out a better form of communication 😆
